# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Helloworld < Formula
  desc "You use the helloworld CLI to perform various actions for testing the security of your applications."
  homepage "https://www.helloworld.com"
  version "1.0.65"
  license "MIT"

  on_macos do
    on_intel do
      url "https://tools.helloworld.com/helloworld-cli/helloworld-cli_1.0.65_macosx_arm64.tar.gz"
      sha256 "136380aba9eff37ca1f1f3e35b65b55457fd9e9ccabdc4112263ea4c99aed46f"

      def install
        bin.install "helloworld"
      end
    end
    on_arm do
      url "https://tools.helloworld.com/helloworld-cli/helloworld-cli_1.0.65_macosx_arm64.tar.gz"
      sha256 "ed94e2fe9f5e9d17c671fbe30d262b61779955c1de8831a0a7f8f8e357b52700"

      def install
        bin.install "helloworld"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://tools.helloworld.com/helloworld-cli/helloworld-cli_1.0.65_linux_x86.tar.gz"
        sha256 "7bf24071cb8d7b29519c0d5bfd18d7af45a082e6b0f7adeb13d53ef86c5321e8"

        def install
          bin.install "helloworld"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://tools.helloworld.com/helloworld-cli/helloworld-cli_1.0.65_linux_x86.tar.gz"
        sha256 "f1227b76f7a0af1207cac186f6087d312ff393ab20c7ef3fc71e214cdd0891f8"

        def install
          bin.install "helloworld"
        end
      end
    end
  end

  test do
    system "#{bin}/helloworld --version"
  end
end
