# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Helloworld < Formula
  desc "You use the helloworld CLI to perform various actions for testing the security of your applications."
  homepage "https://www.helloworld.com"
  version "1.0.61"
  license "MIT"

  on_macos do
    on_intel do
      url "https://tools.helloworld.com/helloworld-cli/helloworld-cli_1.0.61_macosx_arm64.tar.gz"
      sha256 "4dc11d63cd174c4dd3018b7461ec79981f05943f23e952f9e31bd493f3461f15"

      def install
        bin.install "helloworld"
      end
    end
    on_arm do
      url "https://tools.helloworld.com/helloworld-cli/helloworld-cli_1.0.61_macosx_arm64.tar.gz"
      sha256 "4bf7e49c6f4a3d799bb178c71d4a3e422f9863d2c0035b12f94137baf689c736"

      def install
        bin.install "helloworld"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://tools.helloworld.com/helloworld-cli/helloworld-cli_1.0.61_linux_x86.tar.gz"
        sha256 "8921a3337a48095b5e7a21869db8eecb153f9cf4f55fe571c98f8b637273ec0a"

        def install
          bin.install "helloworld"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://tools.helloworld.com/helloworld-cli/helloworld-cli_1.0.61_linux_x86.tar.gz"
        sha256 "09f5db42405dd5792ed1b408f66a72b7fafe02e189f806d7e8d785f86f9ff81d"

        def install
          bin.install "helloworld"
        end
      end
    end
  end

  test do
    system "#{bin}/helloworld --version"
  end
end
