# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Veracode < Formula
  desc "You use the Veracode CLI to perform various actions for testing the security of your applications."
  homepage "https://www.veracode.com"
  version "2.13.3"
  license "MIT"

  on_macos do
    url "https://tools.veracode.com/veracode-cli/veracode-cli_2.13.3_macosx_arm64.tar.gz"
    sha256 "c96dd593b7b5798c78846f6471bec8ea1e33462c4b0a8742e7c642c6da40c000"

    def install
      bin.install "veracode"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://tools.veracode.com/veracode-cli/veracode-cli_2.13.3_linux_x86.tar.gz"
      sha256 "d8d4a6c41971fedc114ad157c96a1f9ad148edc9c3664d625b94fcef9dbedf65"

      def install
        bin.install "veracode"
      end
    end
    if Hardware::CPU.intel?
      url "https://tools.veracode.com/veracode-cli/veracode-cli_2.13.3_linux_x86.tar.gz"
      sha256 "8352dc040ba17cfc85c4271276d5a86a3917af40373cfef539d0c7a86451c774"

      def install
        bin.install "veracode"
      end
    end
  end

  test do
    system "#{bin}/veracode --version"
  end
end
