# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Veracode < Formula
  desc "You use the Veracode CLI to perform various actions for testing the security of your applications."
  homepage "https://www.veracode.com"
  version "2.13.3"
  license "MIT"

  on_macos do
    url "https://tools.veracode.com/veracode-cli/veracode-cli_2.13.3_macosx_arm64.tar.gz"
    sha256 "b70b9c0ec9c1b5af881dd31da1d492f673f722a63dd41d11f330d82062082f31"

    def install
      bin.install "veracode"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://tools.veracode.com/veracode-cli/veracode-cli_2.13.3_linux_x86.tar.gz"
      sha256 "76f2909e68634eda1ff563d15990a5f1282ae3ce8531dc2b47078d2da072ccc9"

      def install
        bin.install "veracode"
      end
    end
    if Hardware::CPU.intel?
      url "https://tools.veracode.com/veracode-cli/veracode-cli_2.13.3_linux_x86.tar.gz"
      sha256 "19fc7939a8a5755d24dfb83b86d31da45b812ad0f9bdfa59a844a3bd4d176ae8"

      def install
        bin.install "veracode"
      end
    end
  end

  test do
    system "#{bin}/veracode --version"
  end
end
