# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VeracodeCli < Formula
  desc "You use the Veracode CLI to perform various actions for testing the security of your applications."
  homepage "https://www.veracode.com"
  version "2.13.3"
  license "MIT"

  on_macos do
    url "https://tools.veracode.com/veracode-cli/veracode-cli_2.13.3_macosx_arm64.tar.gz"
    sha256 "da587fde1784ebf1dbef0ac29d114ce86948f244e34ce25ec328e354f3bc4b9e"

    def install
      bin.install "veracode"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://tools.veracode.com/veracode-cli/veracode-cli_2.13.3_linux_x86.tar.gz"
      sha256 "9042c9b7705ffd14c7969c2caf9c4ea695c5ecc3185dd5825a36d5b1672f4553"

      def install
        bin.install "veracode"
      end
    end
    if Hardware::CPU.intel?
      url "https://tools.veracode.com/veracode-cli/veracode-cli_2.13.3_linux_x86.tar.gz"
      sha256 "57f6bd87ad8f5b3910085fdae1f502b14699bcb3e10003f228c87b059b0f3b9f"

      def install
        bin.install "veracode"
      end
    end
  end

  test do
    system "#{bin}/veracode --version"
  end
end
