# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VeracodeCli < Formula
  desc "You use the Veracode CLI to perform various actions for testing the security of your applications."
  homepage "https://www.veracode.com"
  version "2.13.4"
  license "MIT"

  on_macos do
    url "https://tools.veracode.com/veracode-cli/veracode-cli_2.13.4_macosx_arm64.tar.gz"
    sha256 "cbad41c3fa12d8d639adb1fa4cf1c841f11dbbc735b1a6fecc4cbb341dd95028"

    def install
      bin.install "veracode"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://tools.veracode.com/veracode-cli/veracode-cli_2.13.4_linux_x86.tar.gz"
      sha256 "32fc65b0c4677240c92b86dbbda03d1d7b2ed336b4c9b6017d7766e3c3da47f9"

      def install
        bin.install "veracode"
      end
    end
    if Hardware::CPU.intel?
      url "https://tools.veracode.com/veracode-cli/veracode-cli_2.13.4_linux_x86.tar.gz"
      sha256 "03f5b8f66f20f9f558604f4820453e2a2603fb76dc9b00a957cf2de26072985f"

      def install
        bin.install "veracode"
      end
    end
  end

  test do
    system "#{bin}/veracode --version"
  end
end
